-- DEPRECATED: the schema is now managed by versioned migrations.
-- See the migrations/ folder and run `python migrate.py`.
-- This file is kept only as a quick reference and is not applied automatically.
